### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by 2003lulu** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-2003lulu#1]
[Infografia antonia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-2003lulu/files/15299037/Infografia.antonia.pdf)

**Comment by josealfredo79** [comment]
calificacion..????

**Comment by josealfredo79** [comment]
Calificacion 19
